class CONST:
    MAX_CATEGORY_LIMIT = 6
    MAX_TITLE_LENGTH = 100
    MAX_TEXT_LENGTH = 200
    MIN_TEXT_LENGTH = 10
    MAX_PAGE_SIZE = 30
    TRUNC_POST_TEXT = 20
    DEFAULT_PAGE = 1
    DEFAULT_PAGE_SIZE = 5
    MIN_PAGE_SIZE = 1
